### ISSUE TITLE
Integrate into WordPress?

### ISSUE THREAD

**Issue by abaney** [neokoenig/jQuery-gridmanager#28]
My thought is to use jQuery-gridmanager in conjunction with the WordPress editor so that all the functionality of the WP editor (formatting, media, shortcodes, etc.) are available for use within the grid system of gridmanager. Has this been integrated into WordPress?  Does anyone have any thoughts as to how to accomplish this?

**Comment by neokoenig** [comment]
It wouldn't be impossible - you're up against visual composer etc (commercial plugins) mind: that one was sort of the inspiration for this, but to build something for any application. v0.3.x means you can access all the inbuilt functions in gridmanager, and extend and add your own callbacks, so it should be possible to add (rendered) shortcode support. Bear in mind this plugin is changing a _lot_ at the moment and is very much in active development, so it might be prudent to hold off for a little bit whilst the feature set settles.

**Comment by abaney** [comment]
Thanks @neokoenig. It's funny that you mention Visual Composer. I purchased that plugin, and it's actually the reason why I'm looking into other options. VC is really the best option (for now) to create responsive, fluid grid layouts in web pages. Unfortunately, it has too many stylizing options that should really be the job of a proper theme styling, and VC has too many content block options. I've been able to disable unneeded content blocks with PHP, however, I'm looking for something that uses as much native WordPress functionality as possible. The WP editor works with images, galleries, video, text formatting, links, horizontal rules, shortcodes, etc. and it would be better not to add more code with extra sets of content blocks when WordPress does all this natively.

I really like how you've made the interface for gridmanager easy to understand and intuitive. The buttons could be made a little bigger for easier / quicker clicking, but other than that, you've done an absolutely amazing job!

I'll keep an eye on this project to see if it will be developed for better / more stable use with WordPress. A plugin would be great. Actually, integrating a column system like this into WP core would be the best! Thanks again!

**Comment by DHoffm** [comment]
Hi abaney good that someone is starting to build this for wordpress. I'm curently working on a Joomla Editor based on neo's gridmanager. It's not not the current state but its a start.(no nested functionality, no missing responsive bootstrap classes etc.). Might be helpful to you anyway: https://github.com/DHoffm/Bootstrap-editor

**Comment by neokoenig** [comment]
Thanks @abaney !
- just a few notes - 
  re: button size: there's a branch I did yesterday which adds full LESS Support and theming: so on the next release you'll be able to change the button size easily enough. The real challenge is now figuring out the best way to deal with lots of column buttons - once you get nesting, and the columns get small they become unwieldy: so I'll need to come up with a solution for that (really, the whole row settings drawer etc needs to be tabbed or something).

re: content blocks - we are heading 'that way' - i.e, having distinct stackable (and sortable) editable regions within a column: the default would just be a standard editable field, but the idea is that you could extend and add whatever 'blocks' you want: we'd try and provide some sensible default add-ons of course, but they'd be optional. It's a difficult balance between allowing TinyMCE / Ckeditor etc to add the additional functionality (i.e in a single block), vs implementing your own - there's a danger you could reinvent the wheel. Another issue is how you retain and identify custom regions in the resultant code. For the default editable region we've gone with non-invasive html comments (bit like dreamweaver templates), as then they'd at least be easily stripped out if required.
