### ISSUE TITLE
todo: disable save function when in codeview

### ISSUE THREAD

**Issue by neokoenig** [neokoenig/jQuery-gridmanager#30]
Saving whilst in codeview basically saves 
`<textarea cols="130" rows="25" style="margin-top: 0px; margin-bottom: 0px; height: 1117px;"></textarea>`

instead of the actual content, as it does the GM cleanup.

**Comment by userabuser** [comment]
@neokoenig Can you explain why you want to actually disable the save function when in source/code view?

[My PR](https://github.com/neokoenig/jQuery-gridmanager/pull/33) mitigates such a need to do so, however I am curious as to whether you had some other reason behind the suggestion that I might be missing?

**Comment by neokoenig** [comment]
Your solution is spot on - many thanks for the fix.
Don't worry about the unit tests bit, we're still writing them :)

**Comment by userabuser** [comment]
@neokoenig Thought as much... I'm following anyway so keep me in the loop when they drop as I have many other contributions to add.

Keep up the good work.
