### ISSUE TITLE
Save with post - question

### ISSUE THREAD

**Issue by pluis3103** [neokoenig/jQuery-gridmanager#38]
Hi,
I have a question, if I have a textarea with ckeditor I need only give a name to the textarea and get the post when I submit the form.
What I want is to do the same thing with the gridmanager, but this being a canvas as I do to collect this data from the post without being for ajax?

Thanks

**Comment by DHoffm** [comment]
Are you asking for a function that returns the html. If so I modified the gridmanager.js on my project to support that. You can have a look here: https://github.com/DHoffm/Bootstrap-editor/blob/master/profil_bootstrap_editor/js/gridmanager/gridmanager.js

I modified the  gm.deinitCanvas function by adding a parameter to just return the html and copy it via JQuery to a textarea which is saved on post
.
Be aware that my gridmanager is not in sync with the current state of the project.

**Comment by neokoenig** [comment]
Here's a simple example using a hidden form field: this way means you don't have to touch the gridmanager.js core:
https://gist.github.com/neokoenig/0112bf45d481283c8f9d
