### ISSUE TITLE
Problem with an ajax call

### ISSUE THREAD

**Issue by matheuslc** [neokoenig/jQuery-gridmanager#39]
Hello, first, awesome work, thank you.

I have a problem with the plugin, my pages are called with an ajax call, at the first time was ok, but when I make another ajax call the button tools (".gm-tools") are duplicated. You have some tip to me fix this?

![screenshot from 2014-09-04 10 54 16](https://cloud.githubusercontent.com/assets/4161171/4150187/9b01c732-343b-11e4-915b-a5cdd4c5ab38.png)

![screenshot from 2014-09-04 10 57 43](https://cloud.githubusercontent.com/assets/4161171/4150188/9b03e152-343b-11e4-9ec6-13d1ced8ca78.png)

**Comment by neokoenig** [comment]
Can you share the code you're using to load in the initial ajax content? (and exactly which version?)

Sounds like the content which Gridmanager is being activated on either already has the gridmanager tool markup in it, or that the activateCols function is firing twice...

**Comment by matheuslc** [comment]
I fixed the bug (maybe not a bug, maybe I made a wrong implementation).

I made a variable called 'executed' that has been set true when 'gm.init' has been executed. So, I just execute 'gm.initDefaultButtons' when the 'executed' is false (preventing the duplication).

**Comment by neokoenig** [comment]
Glad you found the issue, but you may find it better to do gm.reset(), which will remove all the markup/buttons etc, then reapply them. That way all your markup will go through the proper methods.
