### ISSUE TITLE
problem with TinyMCE

### ISSUE THREAD

**Issue by danibiza** [neokoenig/jQuery-gridmanager#41]
Hi, I have a problem when change view button to edit source code or any other, I see that you insert this code automatically 
< input name = "mce_0" value = "< p> New Content </ p>" type = "hidden"> I do not understand why.

any solution?

![sin titulo](https://cloud.githubusercontent.com/assets/6940922/4189383/cff37358-377b-11e4-97e6-b6e2c9aef50e.jpg)

**Comment by neokoenig** [comment]
Which version of tinymce are you using? Anything prefixed with mce has been put there by tinymce so we need to strip it out: first time I've seen it do an input field though!

**Comment by danibiza** [comment]
I have the latest version, do not understand why this happens....

**Comment by neokoenig** [comment]
Hmm, I can't replicate this on 4.1.2 or 4.1.5: if you try the demo - http://neokoenig.github.io/jQuery-gridmanager/demo/tinymce.html do you get the same behaviour? (I don't, but I'm wondering if you follow the same steps on that version whether you can tell me how it happens).

Without seeing your implementation of gridmanager, it's hard to diagnose: if you're trying to do this within a CMS, it might be the CMS is loading TinyMCE in a different way which clashes with gridmanager's implementation.

**Comment by rpestana** [comment]
Hi!

That happens to me too. But in your demo don't happens.

Danibiza and neokoenig, any suggestion?

<input value="<p><img style=&quot;float: right;&quot; src=&quot;../../../../website/img/products/product5/fig-3.png&quot; alt=&quot;&quot; width=&quot;247&quot; height=&quot;254&quot; /></p>" name="mce_0" type="hidden">

This are what I'm using tinymce 4.1.2 version:
    <script src="/web/js/bootstrap.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/tinymce/4.1.2/tinymce.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/tinymce/4.1.2/jquery.tinymce.min.js"></script>
    <script src="/web/js/jquery.gridmanager.js"></script>

**Comment by neokoenig** [comment]
Well, my previous suggestion was that TinyMCE might be being configured before reaching the editor via a Content management system configuration...

Again, I need to know which versions so I can test...

**Comment by rpestana** [comment]
Hi neokoenig!

My TinyMCE is 4.1.5,  JQuery is 2.0.2 and JQueryUi is 1.10.3
I'm not using any CMS. But I'm using Datatables and others jquery plugins.

I will see again your demo code, maybe I fault in something.

**Comment by neokoenig** [comment]
Closing, but feel free to reopen.
