### ISSUE TITLE
Delete of row does not work in ie.

### ISSUE THREAD

**Issue by kevgit** [neokoenig/jQuery-gridmanager#42]
Problem in Internet Explorer because of $ sign is missing.
When you delete a row or column, it seems that it disappear, but if you add another row or column, the old row or column will show again.

Running IE with developer tools F12 on consol, I got this error: Object doesn't support property or method 'remove'

The problem can be solved by a little change in gridmanager.js:

---

// Remove a col or row
}).on("click", "a.gm-removeCol", function(){
   $(this).closest("." +gm.options.gmEditClass).animate({opacity: 'hide', width: 'hide', height: 'hide'}, 400, function(){this.remove();});
     gm.log("Column Removed");

}).on("click", "a.gm-removeRow", function(){
   gm.log($(this).closest("." +gm.options.colSelector));
   $(this).closest("." +gm.options.gmEditClass).animate({opacity: 'hide', height: 'hide'}, 400, function(){
     this.remove();

---

Maybe this can help:

change from:    this.remove();   

To this:     $(this).remove();

**Comment by DHoffm** [comment]
Seem you missed to change it for the column remove function.

}).on("click", "a.gm-removeCol", function(){
               $(this).closest("." +gm.options.gmEditClass).animate({opacity: 'hide', width: 'hide', height: 'hide'}, 400, function(){this.remove();});
                 gm.log("Column Removed");

```
        })
```

**Comment by neokoenig** [comment]
DOH. Yep, thanks @DHoffm ..
