### ISSUE TITLE
Image not align to right and center

### ISSUE THREAD

**Issue by rpestana** [neokoenig/jQuery-gridmanager#45]
Hi! Excellent work. This is very good.

But a small thing is we can't align images to right and center.
I tested in: http://neokoenig.github.io/jQuery-gridmanager/demo/tinymce.html

Future developments: accordions and tabs

Thank you

**Comment by neokoenig** [comment]
Hi - this would be down to how you configure the rich text editor. Image alignment/classes would all be handled in there.

**Comment by rpestana** [comment]
Thank you, for your fast answer, 

I will see the rich text editor configure.
