### ISSUE TITLE
responsive images

### ISSUE THREAD

**Issue by pierrebeitz** [neokoenig/jQuery-gridmanager#46]
Hi, first up i want to thank you for your great work. I always wanted a tool like gridmanager.

We have a problem with editors wanting to center images via text-alignment (which is imho, even in the age of grid systems not a horrible thing to do). Due to the fact that img-responsive is automatically added in the cleanup-function, the centering is prevented (because .img-responsive 'display: block's the image). 

I think the editors (in this case using tinyMCE) should be able to disable the automatic addition of img-responsive.

**Comment by neokoenig** [comment]
It's a fair point: I think what I'll do for 3.2 is add a list of classes/attributes to strip, then that would allow you to override the defaults.

**Comment by neokoenig** [comment]
Ok, have a look at the 0.3.2 branch:
https://github.com/neokoenig/jQuery-gridmanager/tree/0.3.2

There's now a bunch of new options:

```
    // Cols-------------
    removeColClass: "mce-content-body",
    // Attributes need to be space seperated
    removeColAttr: "style spellcheck data-mce-href",
    // Add a class to each column
    addColClass: "",

    // Images-------------
    // Ditto for Images
    removeImgClass: "",
    // Attributes need to be space seperated
    removeImgAttr: "style data-cke-saved-src data-mce-src data-mce-href data-mce-selected",
    // Add this class to every img
    addImgClass: "img-responsive",

    // Links-------------
    // Ditto for Links
    removeAClass: "",
    // Attributes need to be space seperated
    removeAAttr: "data-mce-href data-mce-selected",
    // Add this class to every anchor
    addAClass: "",

    // Misc--------------
    // Force remove divs by id: tinymce putting in tonnes of handles etc
    removeDivsByID: "#mceResizeHandlen,#mceResizeHandlee,#mceResizeHandles,#mceResizeHandlew,#mceResizeHandlenw,#mceResizeHandlene,#mceResizeHandlese,#mceResizeHandlesw",
```

Try setting `addImgClass: ""` and let me know how you get on.

**Comment by pierrebeitz** [comment]
thanks a lot for the quick response! i will give it a try!
