### ISSUE TITLE
Feature : Grid Manager content in form

### ISSUE THREAD

**Issue by Adysone** [neokoenig/jQuery-gridmanager#47]
It would be good to add the possibility to put the Grid Manager content into a form field, or just get the content without posting it in AJAX by the Save button.

**Comment by neokoenig** [comment]
Here's a simple example of how you might do that:
https://gist.github.com/neokoenig/0112bf45d481283c8f9d 

Essentially, you hijack the form submission and put the contents of gridmanager into a hidden field.

**Comment by Adysone** [comment]
Ok thanks. I just have to hide the Save button in CSS and go!
