### ISSUE TITLE
load/save configuration of template

### ISSUE THREAD

**Issue by hans-vb** [neokoenig/jQuery-gridmanager#49]
Hi, i need help. I want push a button and save all data (rows, columns, position, content of box...) of my template in a database. Then i need too a process to load all data again.

Any help?
Thanks

**Comment by neokoenig** [comment]
The save function is designed to accept a url i.e, /save-my-suff/ where it will send a POST request with a "content" key value pair containing the data you need to save.

So depending on the serverside language you're using, you want to setup a URL/page where is that POST request exists, it saves it to the database. It's _highly_ dependent on not only what serverside language you're using, but also if you're using a specific framework etc.

So I use http://luc.ee as a serverside application language and cfwheels as my framework.

My update function might look like : 

```
// /pages/update/8/
public void function update() {
        if(structkeyexists(params, "content")){
            page= model("page").findOne(where="id = #params.key#");
        page.save(); 
        redirectTo(action="index", success="page successfully updated");
     }
}
```

This is obviously highly simplified, and uses Object Relational Management.

So really, more information needed.
