### ISSUE TITLE
demos

### ISSUE THREAD

**Issue by gregCPK** [neokoenig/jQuery-gridmanager#50]
hello, i need help. when i test the demo of jquery-gridmanager, nothing works correctly. the icons do not appear, the tinyMCE and CKeditor doesn't works.

thank you in advance

**Comment by neokoenig** [comment]
If you trying to run the demos via file:// that won't work, needs local host or something.

**Comment by neokoenig** [comment]
Closing as no further comment, feel free to re-open.
