### ISSUE TITLE
Using with WordPress

### ISSUE THREAD

**Issue by abaney** [neokoenig/jQuery-gridmanager#53]
I'm sorry. I think I asked this before, but couldn't find my original question here.  :(

I see that Grid Manager can be used with TinyMCE, however, how would I go about using Grid Manager with TinyMCE in WordPress?  Has anyone done this yet?  If so, how?

Thank you!

**Comment by neokoenig** [comment]
I've not tried it. I'm not sure the version of tinyMCE packaged with WP will work, as I've no idea if it will auto attach to the editable regions - I suspect it won't, as I think it's a highly customized version of tinyMCE.

**Comment by abaney** [comment]
@neokoenig - You're probably right. I researched on Google if anyone else has done this, and it looks like not. Back to the drawing board...  Thanks for your quick reply!
