### ISSUE TITLE
How to turn-off /hide the top bar (that has 12/8-4/6-6 etc. sizes)

### ISSUE THREAD

**Issue by KrishnaPG** [neokoenig/jQuery-gridmanager#54]
Would like to retain the right-hand side preview/markup buttons on the top, but turn-off the size buttons on the left-top - how to do it?

**Comment by neokoenig** [comment]
Two ways:

1) Just hide via CSS: 
`#gm-addnew {display:none;}`

2) Or pass in an empty array to `controlButtons`

```
$("#mycanvas").gridmanager({
     debug: 1,
    controlButtons: []}
);
```

**Comment by KrishnaPG** [comment]
Thanks much @neokoenig It is very helpful.
