### ISSUE TITLE
How to add a custom file browser in ckeditor?

### ISSUE THREAD

**Issue by purplegend** [neokoenig/jQuery-gridmanager#56]
In ckeditor, is very simple integrate a custom file browser as descripted here: http://docs.ckeditor.com/#!/guide/dev_file_browse_upload.
How could integrate this in gridmanager?

**Comment by neokoenig** [comment]
You've got a couple of options:

1) Use custom js config file for CKEditor (http://neokoenig.github.io/jQuery-gridmanager/demo/ckeditor-custom.html) which would allow you to override the default CKeditor configuration and add whatever
`ckeditor: {
         customConfig: "/pathtojs/custom-ckeditor.js"
     }`

2) Use something like CKFinder, and just trigger CKFinder in a custom button in gridmanager - you basically would create a link to open /ckfinder/ckfinder.html?action=js

**Comment by neokoenig** [comment]
Closing, but feel free to reopen if this wasn't the case.
