### ISSUE TITLE
Icon issue

### ISSUE THREAD

**Issue by jiyuwazadsgn** [neokoenig/jQuery-gridmanager#57]
Hi, 

This tool is perfect for my work. I downloaded it but the icons won't show. I try to change the version of font awesome, the icons name but it doesn't work. This is not a browser problem because I can use your demo. Any Idea ? Thanks a lot

**Comment by neokoenig** [comment]
If you open your console, do you get any errors?

**Comment by jiyuwazadsgn** [comment]
No. I downloaded directly the font awesome files and it worked. Same issue with the tinymce editor, I need to change the links. I'm not sure I think it's a version problem.

**Comment by neokoenig** [comment]
It doesn't come with TinyMCE included, as you've noticed, that needs to be provided seperately. There is a an option which tries to load FontAwesome off a CDN:

```
// Custom CSS to load
cssInclude: "//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css",
```

So if you were trying to load the page via file:// that wouldn't work (and would explain what you're seeing).

**Comment by neokoenig** [comment]
Closing, but feel free to reopen if this wasn't the case.
