### ISSUE TITLE
Initializing the Rich Editor on newly appended columns

### ISSUE THREAD

**Issue by TimTruston** [neokoenig/jQuery-gridmanager#60]
Hi, I am currently implementing gridmanager on http://launch.nairobi.io/creator

My issue is when a user add new segments onto the html I am unable to make the bootstrap columns editable by double click. e.g. Click "add segment" -> "headers" -> "header 2"

Basically I there is a step I need to go through to make the newly appended colums gm-editable

Kindly assist me..

**Comment by neokoenig** [comment]
Have you tried calling `gm.reset()` after appending the columns?

**Comment by TimTruston** [comment]
Yes. But it doesnt work

On Wed, May 27, 2015 at 4:45 PM, Tom King notifications@github.com wrote:

> Have you tried calling gm.reset() after appending the columns?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/neokoenig/jQuery-gridmanager/issues/60#issuecomment-105916349
> .

## 

Timothy Mwirabua,
Software Consultant at Nairobi.IO http://nairobi.io/
Founder and Web Developer at CHIPPP http://chippp.com/
(+254) 711451409 | Twitter https://twitter.com/techytimo | Linkedin
http://linkedin.com/in/techytimo/

**Comment by TimTruston** [comment]
Around line 400 on http://launch.nairobi.io/assets/js/jquery.gridmanager.js
My code is like:

```
fetchTemplate(category, index).done(function() {
                        if (temp = $.parseHTML(template)) {
                            $('#gm-canvas .page-wrapper').prepend(template = $('<section/>', {
                                "class": 'segment'
                            }).html(temp))
                        };
                        gm.reset();
                    });
```

**Comment by neokoenig** [comment]
I'm afraid you've changed the core source code so much I can't really work out what you're doing.
