### ISSUE TITLE
Can we have only few columns to be uneditable in a row

### ISSUE THREAD

**Issue by dskumar001** [neokoenig/jQuery-gridmanager#61]
Hi,
I need some of the columns content need not to be changed. So, Can i have only few columns to be uneditable in a row.

I tried with editableRegionEnabled as false. But it is making all columns as uneditable.
Please help me out.

Thanks

**Comment by neokoenig** [comment]
Hmm, it's really not built to do that. The only way I can think of is by adding a certain class, i.e like 'uneditable' to the column and then manually removing the GM specific classes on load. It's probably not going to work though, as when you do things like switch to preview mode and back again, or code view, you'll re-run the activation process etc.

You might be able to do it via the filterCallback option ?

**Comment by dskumar001** [comment]
Thanks neokoenig for quick response.

If at all we don't provide switching from preview mode and back again, or code view, Will this be possible by  adding certain classes

**Comment by neokoenig** [comment]
Ok, this is a bit of a ugly hack, and only works if you don't use a rich text editor;
The idea is any column with `.noneditable` has it's editable functionality removed on the `filterCallback`.
It's still draggable, but the actual content isn't editable 

https://gist.github.com/neokoenig/1614b229cdbbba5799d4

**Comment by dskumar001** [comment]
Thanks a lot neokoenig. It will be very helpful for me to move on further.
