### ISSUE TITLE
Preview in mobile and tablet not working for me

### ISSUE THREAD

**Issue by 2braincells2go** [neokoenig/jQuery-gridmanager#70]
Firstly, great job and thanks for sharing with the community.

Was checking out your demos for tiny and ckeditors. When previewing (or in edit mode) nothing happens as in screen resize when choosing mobile or tablet. Screen seems like it wants to resize but always stays in desktop mode.

Think this would be an excellent teaching tool for coding bootstrap layouts. Seems simple enough for classroom usage but would need the phone/tablet working.

Any ideas or am I just missing something?

Cheers!

**Comment by neokoenig** [comment]
So yes, it doesn't resize the viewport when you change modes - but it does switch to altering the various classes underneath. So when you're in 'mobile', when you change the column widths, it changes the `col-sm-6` classes etc (that's configurable in the options), and when in tablet, the 'col-md-x', and desktop, the 'col-lg-x' sizes. The whole thing is also an option, so you can turn off that behaviour if required.

**Comment by 2braincells2go** [comment]
I got it now Tom, my bad.

Got to figure out a way to make it resize. This will be an excellent teaching tool. Simplest way I have ever found.

Thanks for the fast reply and have a great day.

Woody

**Comment by neokoenig** [comment]
If you're interested in the resizing bit, do check out http://responsive.victorcoulon.fr/ as a bookmarklet
