### ISSUE TITLE
Large Desktop,  Landscape & Portrait View in right corner with mobile and tablet view

### ISSUE THREAD

**Issue by ashishbhattb** [neokoenig/jQuery-gridmanager#72]
Hello,

is that any more option  to handle css for "Large Desktop,  Landscape & Portrait" View As now we can find that in drop down only 3 options are there that is "Desktop, Tablet & Mobile"

We needs more options to fix the settings for different layouts like "Large Desktop,  Landscape & Portrait" for every layout options 

Thanks
Ashish Bhatt

**Comment by neokoenig** [comment]
No. It's up to you to program your own CSS breakpoints in your CSS; this is just a class switcher, so whilst I will probably add a fourth, it's still always going to reflect col-lg, col-md, col-sm, col-xs rather than specific breakpoints.
