### ISSUE TITLE
How to properly pull content of editor without editor's markup?

### ISSUE THREAD

**Issue by harin** [neokoenig/jQuery-gridmanager#76]
I would like to pull just the raw html output of the editor without the mark up of the editor. What is the proper way to do that? I tried:

```
gm.cleanup();
var output = $('#gm-canvas').html();
```

but the output still have some editor classes on it, it seems like the cleanup is not done cleaning up yet when the output pulls the html.

**Comment by harin** [comment]
seems to be able to do it with filterCallback

```
 // set option
filterCallback: saveContent
....
function saveContent(canvas, isInit) {
  if( !isInit ) {
    console.log("Saving content");
    console.log(canvas.html());
    $(inputSelector).val(canvas.html());
  }
}
```

_Update: Actually that also doesn't work :(_

**Comment by neokoenig** [comment]
You can use deInitCanvas(): i.e https://gist.github.com/neokoenig/0112bf45d481283c8f9d

**Comment by harin** [comment]
Thanks
