### ISSUE TITLE
Preview Button?

### ISSUE THREAD

**Issue by daslicht** [neokoenig/jQuery-gridmanager#77]
Hello,
what is the Preview buttons purpose:
http://i.imgur.com/26djCHC.png
Its not doing anything ?

**Comment by neokoenig** [comment]
It's not so much a preview button as allows you to manipulate the specific classes for that device size. i.e, col-sm vs col-md vs col-lg; It can't resize the view port.

**Comment by daslicht** [comment]
Ahh ok got it !
Thank you for this AWESOME Plugin !
