### ISSUE TITLE
Dyanmic layout

### ISSUE THREAD

**Issue by ghost** [neokoenig/jQuery-gridmanager#79]
I love this gridmanager, I'm using this for myself, I was wondering if there is possible to create with dynamic code, such as like after making change column or block, is that possible to save and view that page or refresh load page after changed!

please let me know thanks.

Alidad

**Comment by neokoenig** [comment]
if I understand you correctly, you're wanting to save whenever a change is made? There's no real hook for that I'm afraid, as you'd need to listen for all the onDrop() events from the drag and drop UI, but also monitor all the contents changing, whilst excluding all the gridmanager markup.
