### ISSUE TITLE
Simple way for xs-12

### ISSUE THREAD

**Issue by ddegil** [neokoenig/jQuery-gridmanager#82]
Is there a simple setting to always set xs to col-xs-12? It would be useful if there were an option way to turn off each column size. That way a layout could easily always stack on a phone or tablet.

**Comment by neokoenig** [comment]
Have you tried:

```
addResponsiveClasses: false
```

That disables the auto-adding of additional classes. (Must confess I haven't tried it in a while though :)
That _may_ have some side effects that I've not thought of thought...

**Comment by ddegil** [comment]
Nope. I did that and made a 2 column row and still get col-xs-6 on each.

**Comment by neokoenig** [comment]
Ah right, misunderstood you..Nope, can't think of an easy way to do that, except to only use the md or lg subclasses, as if there's no xs, it should auto-stack under bootstrap 3 I think.

**Comment by ddegil** [comment]
How do I do that?

**Comment by ddegil** [comment]
Ahh, got it! I am using a post of the data to the server. When I call the post function and have this line:
`var gm = $('#IDofGM').gridmanager().data('gridmanager');`
I have to pass in options I used when the page initializes! The options are not kept and reused.

**Comment by neokoenig** [comment]
Yeah, that would reset the options back to default!

**Comment by ddegil** [comment]
Why are the options not kept and reused?

**Comment by neokoenig** [comment]
Well, You're creating a new instance of it in your code above. So you have to pass in the configuration... somehow..

**Comment by ddegil** [comment]
I found a far better way now. I am going to revise my post in how to get the data for a postback.....
