### ISSUE TITLE
Re initiate editor after using appendHTMLSelectedCols

### ISSUE THREAD

**Issue by nomi-ramzan** [neokoenig/jQuery-gridmanager#91]
I am using `version 0.3.1` and I want to add some content using `appendHTMLSelectedCols` method. It is working fine. But I also wanted to edit that code after insertion. But I have to change go to preview then i can edit newly inserted code.

```
var gmElem = 
    $('.grid-manager').gridmanager({
        buttons: [[1,3,1,4,3], [2,8,2], [4,8], [8,4]]
    }).data('gridmanager');
```

Add function is here

```
function add() {
    gmElem.appendHTMLSelectedCols('<p>my content to append to all my selected cols</p>');
}
```

But I can not edit this `p` now until i will not view at lease one time preview.

**Comment by nomi-ramzan** [comment]
I got one way to do that `gmElem.reset();`  is there any better way to do that ?

**Comment by neokoenig** [comment]
yeah, reset will take existing HTML and reparse it, and then reinitialize the grid

**Comment by nomi-ramzan** [comment]
Thank you.
