### ISSUE TITLE
change column sizes..

### ISSUE THREAD

**Issue by dgnzcn** [neokoenig/jQuery-gridmanager#92]
hi, how can i add columns only just col-md-*\*  without col-sm-*\* col-xs-**

**Comment by neokoenig** [comment]
The column widths are dictated by your bootstrap grid sizes. It assumes a 12 column grid, but you can change that to 24. See http://neokoenig.github.io/jQuery-gridmanager/docs/dev/options-reference.html - `colMax` and `colStep`

If you're talking about the preset column layouts, you can pass in `
      controlButtons: [[3,7,1,1], [2,1,2,1,2,1,3], [1,3,1,4,3], [2,8,2], [4,8], [8,4]]` to the config

**Comment by dgnzcn** [comment]
hi, thanks reply..
i created for -12, it add `<div class="row"><div class="column col-md-12 col-sm-12 col-xs-12"></div></div>`
how can i add only md's like this:
`<div class="row"><div class="col-md-12"></div></div>`

**Comment by neokoenig** [comment]
set `addResponsiveClasses` to `false`

**Comment by dgnzcn** [comment]
thanks for reply,
i comment these line and it done.

```
   // colTabletClass: "col-sm-",

    // Generic phone size layout class
    // colPhoneClass: "col-xs-",
```

**Comment by dgnzcn** [comment]
thanks for nice job
